version: "3"
services:
    reverseproxy:
        build:
            context: ./
        image: amokraneabd/reverseproxy
    backend_user:
        build:
            context: ../../udacity-c3-restapi-user
        image: amokraneabd/udacity-restapi-user
    backend_feed:
        build:
            context: ../../udacity-c3-restapi-feed
        image: amokraneabd/udacity-restapi-feed
    frontend:
        build:
            context: ../../udacity-c3-frontend
        image: amokraneabd/udacity-frontend:local
